---
- name: Ansible Playbook execution for SAP S/4HANA installation from source media
  hosts: all
  become: true

  collections:
    - community.sap_launchpad

# Use include_role inside Task block, instead of using roles declaration or Task block with import_roles.
# This ensures Ansible Roles, and the tasks within, will be parsed in sequence instead of parsing at Playbook initialisation
  tasks:

    - name: Set fact x86_64 softwarecenter_search_list_s4hana_install
      set_fact:
        softwarecenter_search_list_s4hana_install: "{{ softwarecenter_search_list_s4hana_install_x86_64 }}"
      when:
        - ansible_architecture == "x86_64"

    - name: Set fact ppc64le softwarecenter_search_list_s4hana_install
      set_fact:
        softwarecenter_search_list_s4hana_install: "{{ softwarecenter_search_list_s4hana_install_ppc64le }}"
      when:
        - ansible_architecture == "ppc64le"

    - name: update etc hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ ansible_default_ipv4.address }}\t{{ ansible_hostname }}.{{ ansible_domain }}\t{{ ansible_hostname }}"
        state: present
      become: yes

    - name: Install Python package manager pip3 to system Python
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Install Python package manager lxml to system Python when ppc64le
      ansible.builtin.package:
        name:
        - python3-lxml
        - libxslt-devel
        - libxml2-devel
        state: present
      when:
        - ansible_architecture == "ppc64le"

    - name: Install Python dependency wheel to system Python
      ansible.builtin.pip:
        name:
          - wheel
#        executable: pip3.6

    - name: Install Python dependencies for Ansible Modules to system Python
      ansible.builtin.pip:
        name:
          - urllib3
          - requests
          - beautifulsoup4
          - lxml
#        executable: pip3.6

    - name: Create directories if does not exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - "{{ sap_install_media_detect_directory }}"
        - "{{ sap_hana_install_software_directory }}"

# Use task block to call Ansible Module
    - name: Execute Ansible Module with system Python to download additional installation media
      community.sap_launchpad.software_center_download:
        suser_id: "{{ suser_id }}"
        suser_password: "{{ suser_password }}"
        softwarecenter_search_query: "{{ item }}"
        dest: "{{ sap_install_media_detect_directory }}"
      with_items: "{{ softwarecenter_search_list_s4hana_install }}"
#      vars:
#        ansible_python_interpreter: python3.6

# Use task block to call Ansible Module
    - name: Execute Ansible Module with system Python to get installation files list from SAP Maintenance Planner for an SAP S/4HANA installation
      community.sap_launchpad.maintenance_planner:
        suser_id: "{{ suser_id }}"
        suser_password: "{{ suser_password }}"
        transaction_name: "{{ transaction_name }}"
      register: sap_maintenance_planner_basket_register
#      vars:
#        ansible_python_interpreter: python3.6
#   - debug:
#       msg:
#         - "{{ sap_maintenance_planner_basket_register.download_basket }}"

# Use task block to call Ansible Module
    - name: Execute Ansible Module with system Python to download files returned from SAP Maintenance Planner for an SAP S/4HANA installation
      community.sap_launchpad.software_center_download:
        suser_id: "{{ suser_id }}"
        suser_password: "{{ suser_password }}"
        download_link: "{{ item.DirectLink }}"
        download_filename: "{{ item.Filename }}"
        dest: "{{ sap_install_media_detect_directory }}"
      loop: "{{ sap_maintenance_planner_basket_register.download_basket }}"


    - name: Execute Ansible Role sap_install_media_detect
      include_role:
        name: { role: community.sap_install.sap_install_media_detect }

    - name: Execute Ansible Role sap_general_preconfigure
      include_role:
        name: { role: community.sap_install.sap_general_preconfigure }

    - name: Execute Ansible Role sap_netweaver_preconfigure 
      include_role:
        name: { role: community.sap_install.sap_netweaver_preconfigure }

    - name: Execute Ansible Role sap_hana_preconfigure 
      include_role:
        name: { role: community.sap_install.sap_hana_preconfigure }

    - name: Execute Ansible Role sap_hana_install 
      include_role:
        name: { role: community.sap_install.sap_hana_install }

    - name: Execute Ansible Role sap_swpm with SAP S/4HANA One Host installation from source media
      include_role:
        name: { role: community.sap_install.sap_swpm }

#    - name: Execute Ansible Role sap_profile_update to update Profile for ICM HTTPS
#      include_role:
#        name: { role: community.sap_operations.sap_profile_update }

#    - name: Execute Ansible Role sap_control to restart SAP System/s for Profile update changes
#      include_role:
#        name: { role: community.sap_operations.sap_control }
#      vars:
#        sap_control_function: "restart_all_sap"
