name: Terraform Validate Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  terraform_validate:
    name: 'Terraform Validate ALL'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        terraform_ver: [~1.0.0, ~1.1.0, ~1.2.0, ~1.3.0]
        terraform_module_parent: [all, aws_ec2_instance, ibmcloud_vs, ibmcloud_powervs, ibmpowervc, msazure_vm, vmware_vm]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: ${{ matrix.terraform_ver }}
      - name: Terraform Init
        id: init
        run: |
          cd "./${{ matrix.terraform_module_parent }}"
          for d in */; do
            cd "$d"
            terraform init
            cd ..
          done
      - name: Terraform Validate
        id: validate
        run: |
          cd "./${{ matrix.terraform_module_parent }}"
          for d in */; do
            cd "$d"
            terraform validate -no-color
            cd ..
          done
